# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-29 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('penulis', models.CharField(max_length=54)),
                ('penerbit', models.CharField(max_length=40)),
            ],
        ),
    ]
