# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-29 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0003_kelompok'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='Kelompok_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.Kelompok'),
        ),
    ]
